## Loading data in pandas

In [1]:
import pandas as pd
test = pd.read_csv("Test.csv")
test

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type
0,FDW58,20.750,Low Fat,0.007565,Snack Foods,107.8622,OUT049,1999,Medium,Tier 1,Supermarket Type1
1,FDW14,8.300,reg,0.038428,Dairy,87.3198,OUT017,2007,NaN,Tier 2,Supermarket Type1
2,NCN55,14.600,Low Fat,0.099575,Others,241.7538,OUT010,1998,NaN,Tier 3,Grocery Store
3,FDQ58,7.315,Low Fat,0.015388,Snack Foods,155.0340,OUT017,2007,NaN,Tier 2,Supermarket Type1
4,FDY38,NaN,Regular,0.118599,Dairy,234.2300,OUT027,1985,Medium,Tier 3,Supermarket Type3
...,...,...,...,...,...,...,...,...,...,...,...
5676,FDB58,10.500,Regular,0.013496,Snack Foods,141.3154,OUT046,1997,Small,Tier 1,Supermarket Type1
5677,FDD47,7.600,Regular,0.142991,Starchy Foods,169.1448,OUT018,2009,Medium,Tier 3,Supermarket Type2
5678,NCO17,10.000,Low Fat,0.073529,Health and Hygiene,118.7440,OUT045,2002,NaN,Tier 2,Supermarket Type1
5679,FDJ26,15.300,Regular,0.000000,Canned,214.6218,OUT017,2007,NaN,Tier 2,Supermarket Type1
5680,FDU37,9.500,Regular,0.104720,Canned,79.7960,OUT045,2002,NaN,Tier 2,Supermarket Type1

# Missing Value

In [3]:
test.isna().sum()

Item_Identifier                 0
Item_Weight                   976
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  1606
Outlet_Location_Type            0
Outlet_Type                     0
dtype: int64

In [36]:
#We can see that Item_Weight and Outlet_Size have missing values. We can fill them using mean and mode

In [4]:
test['Item_Weight'] = test['Item_Weight'].fillna(test['Item_Weight'].mean())
  
# replacing missing values in price column
# with median of that column
test.fillna(test['Outlet_Size'].mode()[0], inplace=True)

In [5]:
#Now, no missing values.
test.isna().sum()

Item_Identifier              0
Item_Weight                  0
Item_Fat_Content             0
Item_Visibility              0
Item_Type                    0
Item_MRP                     0
Outlet_Identifier            0
Outlet_Establishment_Year    0
Outlet_Size                  0
Outlet_Location_Type         0
Outlet_Type                  0
dtype: int64

# Feature Preprocessing, Encoding, Scaling

In [40]:
test

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.200,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,Medium,Tier 3,Grocery Store,732.3800
4,NCD19,8.930,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
...,...,...,...,...,...,...,...,...,...,...,...,...
8518,FDF22,6.865,Low Fat,0.056783,Snack Foods,214.5218,OUT013,1987,High,Tier 3,Supermarket Type1,2778.3834
8519,FDS36,8.380,Regular,0.046982,Baking Goods,108.1570,OUT045,2002,Medium,Tier 2,Supermarket Type1,549.2850
8520,NCJ29,10.600,Low Fat,0.035186,Health and Hygiene,85.1224,OUT035,2004,Small,Tier 2,Supermarket Type1,1193.1136
8521,FDN46,7.210,Regular,0.145221,Snack Foods,103.1332,OUT018,2009,Medium,Tier 3,Supermarket Type2,1845.5976
8522,DRG01,14.800,Low Fat,0.044878,Soft Drinks,75.4670,OUT046,1997,Small,Tier 1,Supermarket Type1,765.6700

In [6]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
test['Outlet_Establishment_Year'] = le.fit_transform(test['Outlet_Establishment_Year'])

In [7]:
test['Item_Fat_Content'] = le.fit_transform(test['Item_Fat_Content'])

In [8]:
test['Outlet_Size'] = le.fit_transform(test['Outlet_Size'])

In [9]:
test['Outlet_Location_Type'] = le.fit_transform(test['Outlet_Location_Type'])

In [10]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
test['Item_Weight'] = scaler.fit_transform(test[['Item_Weight']])
test['Item_MRP'] = scaler.fit_transform(test[['Item_MRP']])

In [11]:
import category_encoders as ce

encoder = ce.BinaryEncoder(cols=['Item_Type'])
test = encoder.fit_transform(test)

In [12]:
encoder = ce.BinaryEncoder(cols=['Outlet_Type'])
test = encoder.fit_transform(test)

encoder = ce.BinaryEncoder(cols=['Outlet_Identifier'])
test = encoder.fit_transform(test)

In [13]:
test.drop(columns = ['Item_Identifier'], axis = 1, inplace = True)

In [14]:
test

,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type_0,Item_Type_1,Item_Type_2,Item_Type_3,Item_Type_4,Item_MRP,Outlet_Identifier_0,Outlet_Identifier_1,Outlet_Identifier_2,Outlet_Identifier_3,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type_0,Outlet_Type_1,Outlet_Type_2
0,0.964275,1,0.007565,0,0,0,0,1,0.323413,0,0,0,1,4,1,0,0,0,1
1,0.222983,4,0.038428,0,0,0,1,0,0.235849,0,0,1,0,7,1,1,0,0,1
2,0.598095,1,0.099575,0,0,0,1,1,0.894140,0,0,1,1,3,1,2,0,1,0
3,0.164335,1,0.015388,0,0,0,0,1,0.524488,0,0,1,0,7,1,1,0,0,1
4,0.484706,2,0.118599,0,0,0,1,0,0.862069,0,1,0,0,0,1,2,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5676,0.353974,2,0.013496,0,0,0,0,1,0.466011,0,1,0,1,2,2,0,0,0,1
5677,0.181304,2,0.142991,0,1,1,1,1,0.584637,0,1,1,0,8,1,2,1,0,0
5678,0.324204,1,0.073529,0,0,1,1,0,0.369798,0,1,1,1,5,1,1,0,0,1
5679,0.639774,2,0.000000,0,1,1,1,0,0.778487,0,0,1,0,7,1,1,0,0,1
5680,0.294433,2,0.104720,0,1,1,1,0,0.203778,0,1,1,1,5,1,1,0,0,1

# Loading these models from pickle

In [15]:
import pickle

# Load Linear Regression Model
with open('linear_regression.pkl', 'rb') as file:
    linear_reg_model = pickle.load(file)


# Load Lasso Regression Model
with open('lasso.pkl', 'rb') as file:
    lasso_reg_model = pickle.load(file)

# Load Random Forest Model
with open('random_forest.pkl', 'rb') as file:
    random_forest_model = pickle.load(file)

# Load XGBoost Model
with open('xgboost.pkl', 'rb') as file:
    xgboost_model = pickle.load(file)

In [20]:
lr_predictions = list(linear_reg_model.predict(test))

In [17]:
lasso_predictions = list(lasso_reg_model.predict(test))

In [19]:
rf_predictions = list(random_forest_model.predict(test))

In [21]:
xg_predictions = list(xgboost_model.predict(test))